title: Kira's Poetry
description: A collection of my words

# Remove the theme line completely (GitHub defaults to no theme if none is specified)

plugins:
  - jekyll-optional-front-matter

include:
  - poems

defaults:
  - scope:
      path: "poems"
    values:
      layout: "default"
