title: Kira's Poetry
description: A collection of my words

plugins:
  - jekyll-optional-front-matter

include:
  - poems

defaults:
  - scope:
      path: "poems"
    values:
      layout: "default"
      sitemap: true
